### ISSUE TITLE
Isn't showing in custom cards

### ISSUE THREAD

**Issue by tripplehelix** [custom-cards/nintendo-wishlist-card#5]
I would like to use this for [Steam Wishlist Integration]( https://github.com/boralyl/steam-wishlist) but it isn't showing up. Is it required to install the [Nintendo Wishlist Sensor](https://github.com/custom-components/sensor.nintendo_wishlist) for this to work?

Installing via hacs.

**Comment by boralyl** [comment]
You just need to install this card and the steam wishlist integration.  Then you can display them in your dashboard like so:

```yaml
  - type: custom:nintendo-wishlist-card
    entity: sensor.steam_wishlist
    title: Steam Wishlist
    image_style: backgroundart
    max: 10
```

Assuming you have games on sale that are on your wish list you should see something like this:
![image](https://user-images.githubusercontent.com/109865/130336346-2cdc55b4-d938-4aeb-ae6b-596c5fdce199.png)


After installing the card, you may have to do a force-refresh in the browser in order for the card to show up.
